# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /:year/:month/:day/:title.html
asset_url: /assets

# Setup
title: OIOSO(응소) TECH BLOG
email: info@contec.kr
description: '(주)컨텍 응용소프트웨어팀 기술블로그'
baseurl: /oioso.github.io # the subpath of your site, e.g. /blog
url: https://contec-korea.github.io/oioso.github.io # the base hostname & protocol for your site, e.g. http://example.com

github_username:  Contec-Korea

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-avatar
gems: [jekyll-seo-tag, jekyll-sitemap]

# minima theme settings
show_excerpts: true
minima:
  date_format: "%b %-d, %Y"

collections:
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: tags
    values:
      layout: tag



